# -*- coding: utf-8 -*-
"""CabCancellation(Hk)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnpMmNvMZQ56iKu7UqesSlv0cjbrPT1B

#  Project :- CAB CANCELLATION

This project aims to develop a machine learning model that can predict whether
a cab booking will be canceled. This prediction can help the cab service company reduce operational disruptions and allocate resources more efficiently.

# Problems :
Booking cancellations occur close to the trip start time,causing inconvenience to passengers.

## Importing Important Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score , precision_score, recall_score, f1_score, roc_auc_score

# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('/content/YourCabs.csv')
df.head()

df.shape

df.info()

df.describe()

# Checks for each missing values in dataset
df.isnull().sum()/len(df)*100

"""# Data Cleaning:

"""

df = df.drop(['id','user_id','package_id','to_area_id','from_city_id','to_city_id'],axis=1)

df.shape

# Convert to datetime
df['from_date'] = pd.to_datetime(df['from_date'], errors='coerce')
df['booking_created'] = pd.to_datetime(df['booking_created'], errors='coerce')

# Creating a new feature: time gap between booking and trip (in hours)
df['booking_lead_time'] = (df['from_date'] - df['booking_created']).dt.total_seconds() / 3600

# booking_lead_time is created, the original date columns are no longer needed
df = df.drop(['from_date', 'booking_created'], axis=1)

# Handle Missing Values in the Dataset

# 1. Fill 'from_area_id' with the most frequent area (mode)
df['from_area_id'] = df['from_area_id'].fillna(df['from_area_id'].mode()[0])

# 2. Fill missing 'to_lat' and 'to_long' using median of each 'from_area_id' group
df['to_lat'] = df['to_lat'].fillna(df.groupby('from_area_id')['to_lat'].transform('median'))
df['to_long'] = df['to_long'].fillna(df.groupby('from_area_id')['to_long'].transform('median'))

# 3. Fill any remaining NaNs with overall column median
df['to_lat'] = df['to_lat'].fillna(df['to_lat'].median())
df['to_long'] = df['to_long'].fillna(df['to_long'].median())

# 4. Fill missing values in 'booking_lead_time' with the column median
df['booking_lead_time'] = df['booking_lead_time'].fillna(df['booking_lead_time'].median())

# 4. Final checking
print("-> Total remaining missing values:", df.isnull().sum().sum())

df.isnull().sum()/len(df)*100

"""# Filling the missing values"""

# Fill missing values in 'from_lat' and 'from_long' with the column median
df['from_lat'] = df['from_lat'].fillna(df['from_lat'].median())
df['from_long'] = df['from_long'].fillna(df['from_long'].median())

# Final check for missing values
print("-> Total remaining missing values after handling 'from_lat' and 'from_long':", df.isnull().sum().sum())

df.info()

"""# Encoding :
* **We will use one hot encoding because categorical variable is nominal (no intrinsic order)**
"""

# Show categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns to encode:", cat_cols.tolist())

# numerically stored categorical columns
for col in df.columns:
    if df[col].nunique() < 15 and df[col].dtype in ['int64', 'float64']:
        print(f"{col}: {df[col].unique()}")

"""We will change the data type for numerically stored categorical columns and then perform encoding
* we will not perform encoding on Car_Cancellation because it is our target variable
"""

df['travel_type_id'] = df['travel_type_id'].astype('category')
df['online_booking'] = df['online_booking'].astype('category')
df['mobile_site_booking'] = df['mobile_site_booking'].astype('category')

df_encoded = pd.get_dummies(df, columns=['travel_type_id', 'online_booking', 'mobile_site_booking'], drop_first=True)

"""# Outlier Detection (using boxplot):"""

plt.figure(figsize=(12, 10))
# Plot boxplots one by one

# booking_lead_time
plt.subplot(3, 2, 1)
sns.boxplot(x=df_encoded['booking_lead_time'])
plt.title("Boxplot: booking_lead_time")

# from_lat
plt.subplot(3, 2, 2)
sns.boxplot(x=df_encoded['from_lat'])
plt.title("Boxplot: from_lat")

# from_long
plt.subplot(3, 2, 3)
sns.boxplot(x=df_encoded['from_long'])
plt.title("Boxplot: from_long")

# to_lat
plt.subplot(3, 2, 4)
sns.boxplot(x=df_encoded['to_lat'])
plt.title("Boxplot: to_lat")

# to_long
plt.subplot(3, 2, 5)
sns.boxplot(x=df_encoded['to_long'])
plt.title("Boxplot: to_long")

plt.tight_layout()
plt.show()

"""# Outlier Removal"""

# remove outliers using IQR:

# Define the columns to clean
columns_to_clean = ['booking_lead_time', 'from_lat', 'from_long', 'to_lat', 'to_long']

# Apply IQR method to each column
for col in columns_to_clean:
    Q1 = df_encoded[col].quantile(0.25)
    Q3 = df_encoded[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_encoded = df_encoded[(df_encoded[col] >= lower_bound) & (df_encoded[col] <= upper_bound)]

"""# Scaling :"""

X = df_encoded.drop('Car_Cancellation', axis=1)  # Features
y = df_encoded['Car_Cancellation']               # Target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# To Balance data using SMOTE Technique
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
# Apply to training data
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

print("After SMOTE:")
print("Class 0:", sum(y_train_smote == 0))
print("Class 1:", sum(y_train_smote == 1))

"""# Model Building:

# Logistic Regression
"""

# Train logistic regression on SMOTE-balanced data
model = LogisticRegression(random_state=42)
model.fit(X_train_smote, y_train_smote)

# Predict on the scaled test data
y_pred = model.predict(X_test_scaled)

# Probability scores (for ROC-AUC)
y_proba = model.predict_proba(X_test_scaled)[:, 1]

# Metrics
print("Logistic Regression Evaluation:")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_proba))

# Confusion Matrix :
cm = confusion_matrix(y_test, y_pred)

# Heatmap :
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[0,1], yticklabels=[0,1])
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

print("Classification Report:\n")
print(classification_report(y_test, y_pred))

# Predictions on training and test sets
y_train_pred_lr = model.predict(X_train_scaled)
y_test_pred_lr = model.predict(X_test_scaled)

# Accuracy scores
train_acc_lr = accuracy_score(y_train, y_train_pred_lr)
test_acc_lr = accuracy_score(y_test, y_test_pred_lr)

# Print results
print("Logistic Regression Accuracy Scores:")
print("Train Accuracy:", round(train_acc_lr, 4))
print("Test Accuracy :", round(test_acc_lr, 4))

"""# Decesion Tree"""

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_smote, y_train_smote)

# Predict on test data
y_pred_dt = dt_model.predict(X_test_scaled)

# Get probabilities (for ROC AUC)
y_proba_dt = dt_model.predict_proba(X_test_scaled)[:, 1]

# Print evaluation metrics
print("Decision Tree Evaluation:")
print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))
print("ROC AUC  :", roc_auc_score(y_test, y_proba_dt))

# Confusion Matrix
plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred_dt), annot=True, fmt='d', cmap='Oranges')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Decision Tree - Confusion Matrix")
plt.show()

# Classification report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

# Predictions on training and test sets
y_train_pred_dt = dt_model.predict(X_train_smote)
y_test_pred_dt = dt_model.predict(X_test_scaled)

# Accuracy scores
train_accuracy = accuracy_score(y_train_smote, y_train_pred_dt)
test_accuracy = accuracy_score(y_test, y_test_pred_dt)

# Print results
print("Decision Tree Accuracy Scores:")
print("Train Accuracy:", round(train_accuracy, 4))
print("Test Accuracy :", round(test_accuracy, 4))

"""# Overfitting Exist (Prune the Tree)




"""

# Pruned Decision Tree
pruned_dt_model = DecisionTreeClassifier(
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

# Train on SMOTE-balanced data
pruned_dt_model.fit(X_train_smote, y_train_smote)

# Predict on train and test sets
y_train_pred_pruned = pruned_dt_model.predict(X_train_smote)
y_test_pred_pruned = pruned_dt_model.predict(X_test_scaled)

# Accuracy
print("Pruned Decision Tree Accuracy Scores:")
print("Train Accuracy:", round(accuracy_score(y_train_smote, y_train_pred_pruned), 4))
print("Test Accuracy :", round(accuracy_score(y_test, y_test_pred_pruned), 4))

"""# Model Saving

"""

import joblib
joblib.dump(model, 'logistic_regression_model.pkl')
joblib.dump(dt_model, 'decision_tree_model.pkl')
print("Models saved successfully!")
